default: &default
  pool     : 5
  timeout  : 5000
  encoding : unicode
  adapter  : postgresql
  host     : <%= ENV['DATABASE_HOST'] %>
  username : <%= ENV['DATABASE_USER'] %>
  password : <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: serve1_dev

test:
  <<: *default
  database: serve1_test

production:
  <<: *default
  database: serve1_prod
