# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  excluded_subdomains: [www, admin]
  secret_key_base: faa294f134f45e681fd08921b077e6895d4e54532bbe978929b5341846ea359e81ec1b07676653a712d0ccb36f4e88d8f75959a54e4d0aa02a71f49c3589300c

test:
  excluded_subdomains: [www, admin]
  secret_key_base: df2b41806acddfbe42cb88e5879603ab48eedc3d89456f8868d1b39686b133627a5c49d8d3139fa649aef0105f525a4f94255c611ccfa9c91fd9c04478fb2ace

production:
  excluded_subdomains: [www, admin, serve1-staging, serve1-production]
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
