# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57cd642d2481de4c6fb5acbf94ac42e5838136d0a0873ad92d3b87e5a7e01371ebf21308e38e12267c2dbcd26e30ef07b5b83683068251c3779abbdfc9a80ac2

test:
  secret_key_base: df2b41806acddfbe42cb88e5879603ab48eedc3d89456f8868d1b39686b133627a5c49d8d3139fa649aef0105f525a4f94255c611ccfa9c91fd9c04478fb2ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
